### ISSUE TITLE
Could you please license this project?

### ISSUE THREAD

**Issue by ghost** [mrinalTheCoder/ObjectDetectionApp#1]
Hi Mrinal,

I hope you are well. I am impressed by your work. I am new to machine learning and would like to use some of your code for a college project. I am first looking for your permission to use it.  I am just wondering could you license this project and allow it to be open source? Look forward to hearing from you. Thank you.

Kind regards,

Gary.

**Comment by mrinalTheCoder** [comment]
Sure, I will look into it!

**Comment by ghost** [comment]
Thank you appreciate it.

**Comment by gmurphy97** [comment]
Hi @mrinalTheCoder any updates? 

Thanks,

Regards Gary.

**Comment by ghost** [comment]
Hi Mrinal,

I am sorry to be annoying. I am wondering if you have any updates on a license or could at least you grant me permission to use some of this code? The deadline for my project is this week and I need to know if I can use the code. Be greatly appreciated.

Thank you.

**Comment by mrinalTheCoder** [comment]
Hey Gary, 
Sorry for all the delays, you can go ahead and use the code while I add a license. Just make sure your project is open source as well, and credit the author (me).

**Comment by ghost** [comment]
Thank you very much, I will give you full credit.

**Comment by mrinalTheCoder** [comment]
I have added a gnu gpl license.

**Comment by ghost** [comment]
Thank you very much appreciate it.
